default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode
  username: postgres
  port: 5433

development:
  <<: *default
  database: portal_development

test:
  <<: *default
  database: portal_test

production:
  <<: *default
  database: portal_production
