# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a09e39b605e00f9288086b11835efaf202290d05f52ba8538c2d72d6e0919b278d6dd05bfedd5ef0c930d99bfa9636218a41fa4dcf370527d9cd9fdf97950a3

test:
  secret_key_base: ed1fe397823b38c5e4047dcada1e5a0c0077c51fe93005f52cf2f8049d1ff604bb941bdef68275c5ca6ace30daacc46c5d9fe51d0ffdf35ba36f02c07d21d154

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
